name: Bug Report
description: Сообщить об ошибке в работе GitLab Ping
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Пожалуйста, заполните форму ниже.

  - type: textarea
    id: description
    attributes:
      label: Описание ошибки
      description: Краткое описание проблемы
      placeholder: Опишите, что пошло не так
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
      description: Опишите шаги для воспроизведения ошибки
      placeholder: |
        1. Запустить команду...
        2. Нажать на...
        3. Увидеть ошибку...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      description: Что вы ожидали увидеть
      placeholder: Опишите, что должно было произойти
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Фактическое поведение
      description: Что произошло на самом деле
      placeholder: Опишите, что произошло на самом деле
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Сообщение об ошибке
      description: Полное сообщение об ошибке (если есть)
      render: shell
      placeholder: |
        Traceback (most recent call last):
          File "run_cli.py", line 10, in <module>
            from main import main
        ModuleNotFoundError: No module named 'main'

  - type: input
    id: version
    attributes:
      label: Версия GitLab Ping
      description: Версия программы
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Версия Python
      description: Версия Python
      placeholder: 3.10.6
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Операционная система
      description: Ваша операционная система
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      description: Любая дополнительная информация о проблеме
      placeholder: Конфигурация, логи, скриншоты и т.д.

  - type: checkboxes
    id: terms
    attributes:
      label: Проверка
      description: Пожалуйста, подтвердите следующее
      options:
        - label: Я искал существующие issues перед созданием нового
          required: true
        - label: Я проверил, что использую последнюю версию
          required: true